# Generated by Django 3.1.1 on 2020-09-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('renda', models.FloatField()),
                ('qtd_filhos', models.IntegerField()),
                ('data_nascimento', models.DateTimeField()),
                ('estado_civil', models.CharField(max_length=15)),
                ('tempo_cargo', models.PositiveIntegerField()),
                ('caminho_foto', models.CharField(max_length=150)),
                ('caminho_rg', models.CharField(max_length=150)),
                ('caminho_cpf', models.CharField(max_length=150)),
                ('caminho_comprovante_renda', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=30)),
                ('salario_minimo', models.FloatField()),
                ('salario_maximo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=10)),
                ('ultimo_acesso', models.DateTimeField()),
                ('data_cadastro', models.DateTimeField()),
                ('nivel_acesso', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('data_ficha', models.DateTimeField()),
                ('id_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cadastro')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='polls.usuario')),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operador', to='polls.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cadastro',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cargo'),
        ),
    ]
