# Generated by Django 3.1.1 on 2020-11-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201004_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='credito',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
