# Generated by Django 3.1.1 on 2020-11-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ficha_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='caminho_comprovante_renda',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='caminho_cpf',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='caminho_foto',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='caminho_rg',
        ),
        migrations.AddField(
            model_name='ficha',
            name='caminho_comprovante_renda',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='caminho_cpf',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='caminho_foto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='caminho_rg',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
