# Generated by Django 3.1.1 on 2020-11-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201116_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateTimeField(null=True),
        ),
    ]
