# Generated by Django 3.1.1 on 2020-11-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201116_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='data_nascimento',
        ),
    ]
