# Generated by Django 3.1.1 on 2020-11-16 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_remove_cadastro_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operador', to=settings.AUTH_USER_MODEL),
        ),
    ]
