# Generated by Django 3.1.1 on 2020-11-16 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_auto_20201116_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.cargo'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_comprovante_renda',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_cpf',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_foto',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_rg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='credito',
            field=models.FloatField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operador', to=settings.AUTH_USER_MODEL),
        ),
    ]
