# Generated by Django 3.1.1 on 2020-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201116_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em análise'), ('A', 'Aprovado'), ('R', 'Reprovado')], default='P', max_length=15),
        ),
    ]
