# Generated by Django 3.1.1 on 2020-11-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_auto_20201117_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={},
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.cadastro'),
        ),
    ]
