# Generated by Django 3.1.1 on 2020-11-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201122_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='caminho_comprovante_renda',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', height_field=90, null=True, upload_to='upload_fichas/%Y/%m/%d', width_field=90),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_cpf',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', height_field=90, null=True, upload_to='upload_fichas/%Y/%m/%d', width_field=90),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_foto',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', height_field=90, null=True, upload_to='upload_fichas/%Y/%m/%d', width_field=90),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_rg',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', height_field=90, null=True, upload_to='upload_fichas/%Y/%m/%d', width_field=90),
        ),
    ]
