# Generated by Django 3.1.1 on 2020-11-22 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201122_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_comprovante_renda',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', null=True, upload_to='upload_fichas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_cpf',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', null=True, upload_to='upload_fichas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_foto',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', null=True, upload_to='upload_fichas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_rg',
            field=models.ImageField(blank=True, default='upload_fichas/index.png', null=True, upload_to='upload_fichas/%Y/%m/%d'),
        ),
    ]
