# Generated by Django 3.1.1 on 2020-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201122_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
