# Generated by Django 3.1.1 on 2020-11-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20201123_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='data_nascimento',
        ),
    ]
