# Generated by Django 3.1.1 on 2020-11-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_cadastro_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='qtd_filhos',
            field=models.PositiveIntegerField(),
        ),
    ]
