# Generated by Django 3.1.1 on 2020-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20201124_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='idade',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
