# Generated by Django 3.1.1 on 2020-11-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_cadastro_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='motivo_recusa',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
