# Generated by Django 3.1.1 on 2020-11-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_ficha_motivo_recusa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro (a)', 'Solteiro (a)'), ('Casado (a)', 'Casado (a)'), ('Divorciado (a)', 'Divorciado (a)'), ('Viúvo (a)', 'Viúvo (a)')], default='Solteiro (a)', max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_comprovante_renda',
            field=models.ImageField(default='shalaba', upload_to='upload_fichas/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_cpf',
            field=models.ImageField(blank=True, null=True, upload_to='upload_fichas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_foto',
            field=models.ImageField(default='shalaba', upload_to='upload_fichas/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='caminho_rg',
            field=models.ImageField(default='shalaba', upload_to='upload_fichas/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
