# Generated by Django 3.1.1 on 2020-11-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20201126_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='caminho_cpf',
            field=models.ImageField(blank=True, default='upload_fichas/vazio.png', null=True, upload_to='upload_fichas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='credito',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
